# vim: noai:ts=2:sw=2:et
---

# why use Ubuntu for everything? 'cause it is the cheapest on K5
server:
  image: "{{ k5_images.ubuntu_1404.name }}"
  flavor: "S-1"
  volume_size: "{{ k5_images.ubuntu_1404.min_size }}"
  network: "nx2-network-uk-1b-appslan"
  subnet: "nx2-subnet-uk-1b-appslan"
  security_group: "nx2-uk-1b-appslan"
  group: "docker_engine"
  needs_public_ip: no  
  remote_port_check_regex: "OpenSSH"

ansible_user: "ubuntu"
ansible_connection: "ssh"
ansible_port: 22
ansible_ssh_private_key_file: "~/.ssh/NickCross-uk1b.pem"
 
user_data_file: "userdata/docker_engine"  # updates for pipelining

